### ISSUE TITLE
Schematics Design

### ISSUE THREAD

**Issue by andreagil** [roboticslab-uc3m/Dextra#5]
In order to design the schematics, only the connections are taken into account.

It is assumed that each connector is a box with inputs and output. The schematics are the conections between the pins of that boxes without considering the dimensions of any component or the final design of the final PCB (simply the connections, without taking into account the size of hardware).

Steps:

1) Create connectors for each driver, encoder and for the Teensy following the datasheet information of the pines. The correct orientation is not needed at this stage. (In the schematics presented below, components in the PCB should be rotated 180 º.)
Components connections have been created following the pin information of the spreadsheet:
In the case of the drivers:
![image](https://user-images.githubusercontent.com/47393802/52899569-bc6f5800-31eb-11e9-9ee3-83127d87f00c.png)
In the case of the microcontroller:
![image](https://user-images.githubusercontent.com/47393802/52899575-cf822800-31eb-11e9-9828-0bf77ddf5b14.png)

2) Add the labels to each pin so that KiCad is able to understand each connection among the electronic components.

3) Put an X where there is no connection.

4) Annotate the component. (designator ? is automatically changed by a number)

Final result:
![image](https://user-images.githubusercontent.com/47393802/52899539-66021980-31eb-11e9-8ee9-7c3e825d7bef.png)
Comment: the name of the labels in a schematic usually corresponds to the functionality of each pin. In this case, for simplicity (and because I'm not quite sure of which are the funcionalities of the left pins of the microcontroller), the name of the PINS: PIN0, PIN1... have been used. 

Additional material used for the creation of the schematics:
https://www.youtube.com/watch?v=zK3rDhJqMu0

**Comment by jgvictores** [comment]
Pending: remove via from design

**Comment by jgvictores** [comment]
Pending: join PCBs (divide by row to allow cutting, such as holes for a row of pins)

**Comment by jgvictores** [comment]
> Pending: join PCBs (divide by row to allow cutting, such as holes for a row of pins)

Perhaps manufacturers can do this for us. We'll find out!

**Comment by PeterBowman** [comment]
This design has been validated today on our new right hand PCB. A firmware update is required due to a small change in the Teensy's pinout, see https://github.com/PeterBowman/Dextra/commit/e3cab0e060824f9b8a36afa21fc96b95bcb19211. To be merged soon.

TODO list targeted at future iterations:

* Reverse the Pololu connector pinout, i.e. bring the ground pin back to the left side (so that wires need not to be flipped on their way from the board to the Pololus).
* There are several screw holes, we just need two (top-left and bottom-right). Removing them would leave more room for the CAN transceiver (https://github.com/roboticslab-uc3m/Dextra/issues/2) and the DC/DC converter (https://github.com/roboticslab-uc3m/Dextra/issues/3).

**Comment by PeterBowman** [comment]
Merged into default branch at https://github.com/roboticslab-uc3m/Dextra/commit/cc3cdb3ec0158abe4dacd742bfecd29fd41c0f4c. The obsolete right-hand design was removed (still accessible through commit history).
